<?php

/**
 * Generate PrestaShop legacy-class aliases for phpstan (TWO-25107).
 *
 * PrestaShop core declares its legacy classes as `XCore` (e.g.
 * `ConfigurationCore` in classes/Configuration.php) and generates the
 * plain `X` alias at runtime via PrestaShopAutoload:
 *
 *     eval($type . ' ' . $className . ' extends ' . $className . 'Core {}');
 *
 * phpstan scans the real core sources (scanDirectories in phpstan.neon)
 * so it sees the `XCore` classes with their real signatures, but the
 * runtime-generated `X` aliases don't exist on disk anywhere. This script
 * mirrors the autoloader's aliasing statically: it scans a PrestaShop
 * core checkout for `XCore` declarations and writes a stub file of
 * `<type> X extends XCore {}` declarations for phpstan to scan.
 *
 * Classes that this module overrides (override/classes/**) are skipped,
 * exactly like the runtime autoloader skips alias generation when an
 * override exists — the override file itself declares `X extends XCore`.
 *
 * Usage:
 *   php dev/ci/generate-ps-class-aliases.php <ps-core-root> <output-file>
 *
 * The output file is analysis-only and never loaded at runtime.
 */

declare(strict_types=1);

if ($argc !== 3) {
    fwrite(STDERR, "usage: php {$argv[0]} <ps-core-root> <output-file>\n");
    exit(1);
}

$coreRoot = rtrim($argv[1], '/');
$outFile = $argv[2];
$moduleRoot = dirname(__DIR__, 2);

$classesDir = $coreRoot . '/classes';
if (!is_dir($classesDir)) {
    fwrite(STDERR, "error: {$classesDir} is not a directory (wrong core root?)\n");
    exit(1);
}

// Class names this module overrides — the override file already declares
// the non-Core class, so emitting an alias too would be a duplicate.
$overridden = [];
$overrideDir = $moduleRoot . '/override';
if (is_dir($overrideDir)) {
    $it = new RecursiveIteratorIterator(new RecursiveDirectoryIterator($overrideDir));
    foreach ($it as $file) {
        if ($file->isFile() && $file->getExtension() === 'php') {
            $src = (string) file_get_contents($file->getPathname());
            if (preg_match_all('/^\s*(?:abstract\s+)?class\s+(\w+)\s+extends\s+\w+Core\b/m', $src, $m)) {
                foreach ($m[1] as $name) {
                    $overridden[$name] = true;
                }
            }
        }
    }
}

$aliases = [];
$it = new RecursiveIteratorIterator(new RecursiveDirectoryIterator($classesDir));
foreach ($it as $file) {
    if (!$file->isFile() || $file->getExtension() !== 'php') {
        continue;
    }
    $src = (string) file_get_contents($file->getPathname());
    // Same shape the runtime autoloader indexes: a top-level
    // class/abstract class/interface named <Basename>Core.
    if (!preg_match('/^\s*(?<type>abstract\s+class|class|interface)\s+(?<name>\w+)Core\b/m', $src, $m)) {
        continue;
    }
    $name = $m['name'];
    if ($name !== basename($file->getPathname(), '.php')) {
        continue; // only alias the file's own primary class, like the autoloader
    }
    if (isset($overridden[$name])) {
        continue;
    }
    $aliases[$name] = preg_replace('/\s+/', ' ', $m['type']);
}

ksort($aliases);

$out = "<?php\n\n// Auto-generated by dev/ci/generate-ps-class-aliases.php — do not edit.\n"
    . "// Static mirror of PrestaShopAutoload's runtime `X extends XCore` aliases,\n"
    . "// for phpstan analysis only. Never loaded at runtime.\n\n";
foreach ($aliases as $name => $type) {
    $out .= "{$type} {$name} extends {$name}Core\n{\n}\n\n";
}

if (file_put_contents($outFile, $out) === false) {
    fwrite(STDERR, "error: could not write {$outFile}\n");
    exit(1);
}

fwrite(STDOUT, 'Wrote ' . count($aliases) . " aliases to {$outFile}\n");
